model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    # Point this to the file you downloaded from the link above
    ckpt_path: "/home/avinoamd/roni/BBDM/results/VQGAN/CelebAMaskHQ-f4.ckpt"
    embed_dim: 3        # d=3 for f4 model
    n_embed: 8192       # Z=8192 codebook size
    ddconfig:
      double_z: False
      z_channels: 3     # d=3 for f4 model
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4 ]  # f4 architecture
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0
        disc_num_layers: 3

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /home/avinoamd/roni/BBDM/data_10.01_no_hands/train.txt
        size: 256
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: /home/avinoamd/roni/BBDM/data_10.01_no_hands/val.txt
        size: 256
